environment:
  global:
    PYTHON: "C:\\Python35"
    
  matrix:
  
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      generator: "Visual Studio 17 2022"
      arch: x64
      configuration: Debug
      output_name_postfix: _d
      language_number: 20
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      generator: "Visual Studio 17 2022"
      arch: x64
      configuration: Release
      language_number: 20
  
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: "Visual Studio 16 2019"
      arch: x64
      configuration: Debug
      output_name_postfix: _d
      language_number: 17
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: "Visual Studio 16 2019"
      arch: x64
      configuration: Release
      language_number: 17
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017"
      arch: x64
      configuration: Debug
      output_name_postfix: _d
      language_number: 14
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017"
      arch: x64
      configuration: Release
      language_number: 14

install:
  - git submodule update --init --recursive
  - cmake --version

build_script:
  - ls
  - mkdir build
  - cd build
  - echo %configuration%
  - cmake -G "%generator%" -A "%arch%" "-DCMAKE_BUILD_TYPE=%configuration%" "-DMINIYAML_CPP_VERSION=%language_number%" ..
  - cmake --build . --config %configuration%
   
after_build:
  - cd ../bin
  - mini_yaml_tests%output_name_postfix%.exe
